- name: add mariadb repository key
  apt_key:
    id: "{{ item }}"
    keyserver: "pool.sks-keyservers.net"
  with_items:
    - 177F4010FE56CA3336300305F1656F24C74CD1D8 # MariaDB
    - 4D1BB29D63D98E422B2113B19334A25F8507EFA5 # Percona

- name: add mariadb and percona repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    - "deb [arch=amd64,i386,ppc64el] http://mariadb.mirrors.ovh.net/MariaDB/repo/10.2/debian {{ ansible_distribution_release }} main"
  register: repo

- name: install mariadb-server and percona-xtrabackup
  apt:
    pkg:
      - mariadb-server-10.2
      - mariadb-backup-10.2
    cache_valid_time: 3600

- name: copy mariadb config files
  copy: src="99-zds.cnf" dest="/etc/mysql/conf.d/99-zds.cnf"
  notify: restart mariadb

- name: ensure mysqld is started
  service:
    name: mariadb
    state: started
    enabled: yes

- name: install MySQLdb-python
  apt:
    name: python-mysqldb

- name: create mysql database
  mysql_db:
    name: "{{ mysql.name }}"
    state: present

- name: create mysql user
  mysql_user:
    name: "{{ mysql.user }}"
    password: "{{ mysql.password }}"
    host: localhost
    priv: "{{ mysql.name }}.*:ALL"
    state: present
