---

- name: install app dependencies
  become: true
  action: >
    apt name={{ item }} state=present update_cache=yes
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - build-essential
    - libffi-dev
    - libmariadbclient-dev

- name: should have a {{ appuser }} user
  become: true
  user:
    name: "{{ appuser }}"
    shell: /bin/false
    home: "{{ workdir }}"
    comment: "Zeste de Savoir"

- name: create the needed directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ appuser }}"
    group: "{{ appuser }}"
  with_items:
    - "{{ logdir }}/"
    - "{{ workdir }}/"
    - "{{ workdir }}/data"
    - "{{ workdir }}/data/contents-private"
    - "{{ workdir }}/data/contents-public"
    - "{{ workdir }}/data/media"
    - "{{ workdir }}/data/static"

- name: checkout the application
  become: true
  become_user: "{{ appuser }}"
  git:
    repo: 'https://github.com/zestedesavoir/zds-site.git'
    dest: "{{ workdir }}/app"
    version: "{{ appversion }}-build"

- name: symlink data folders
  become: true
  become_user: "{{ appuser }}"
  file:
    src: "{{ workdir }}/data/{{ item }}"
    dest: "{{ workdir }}/app/{{ item }}"
    state: link
  with_items:
    - contents-private
    - contents-public
    - media
    - static

- name: install requirements in virtualenv
  become: true
  become_user: "{{ appuser }}"
  pip:
    requirements: "{{ workdir }}/app/requirements-prod.txt"
    virtualenv: "{{ workdir }}/virtualenv"
    virtualenv_command: /usr/bin/pyvenv

- name: save wrapper script
  become: true
  become_user: "{{ appuser }}"
  template:
    src: templates/wrapper.j2
    dest: "{{ workdir }}/wrapper"
    mode: '0755'

- name: create app config file
  become: true
  become_user: "{{ appuser }}"
  template:
    src: templates/config.toml.j2
    dest: "{{ workdir }}/config.toml"
