---

- name: should have UTF-8 locales enabled
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - fr_FR.UTF-8
    - en_US.UTF-8

- name: should have some base packages
  become: true
  action: >
    apt name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - git
    - zsh
    - logrotate
    - tmux

- name: set default shell to zsh for root
  user:
    user: root
    shell: /usr/bin/zsh

- name: copy zsh config files
  copy:
    src: "{{ item.src }}"
    dest: "/etc/zsh/{{ item.path }}"
  with_filetree: zsh/
  when: item.state == 'file'

