- name: reload zds
  systemd:
    name: zds
    state: reloaded

- name: restart watchdog
  systemd:
    name: zds-watchdog
    state: restarted

- name: remove maintenance symlink
  file:
    path: "{{ webroot }}/maintenance.html"
    state: absent
