- include_role:
    name: common
    tasks_from: nodejs
  tags:
    - bootstrap

- name: install pm2 globally
  npm:
    name: pm2
    global: yes
  tags:
    - bootstrap

- name: create zmd home directory
  file:
    state: directory
    path: /opt/zmd
    owner: zds
    group: zds
    mode: 0755
  tags:
    - bootstrap

- name: add server package.json
  template:
    src: package.json.j2
    dest: /opt/zmd/package.json
  register: zmd_package
  notify: restart zmd
  tags:
    - bootstrap
    - upgrade

- name: install zmarkdown
  npm:
    name: zmarkdown
    path: /opt/zmd
  when: zmd_package.changed

- name: add zmarkdown unit file
  template:
    src: zmd.service.j2
    dest: /etc/systemd/system/zmd.service
  notify: restart zmd

- name: ensure zmd is running.
  service:
    name: zmd
    state: started
    enabled: yes
  register: zmd_service

- name: check that zmd is running
  uri:
    url: http://localhost:27272/
    return_content: yes
  register: this
  delay: 1
  retries: 10
  until: "'zmd is running' in this.content"
